### ISSUE TITLE
In SearchSearchItemList class 'Serial' attribute not available

### ISSUE THREAD

**Issue by chaudharyrr** [CiscoDevNet/intersight-python#18]
While using Intersight API to get various attributes using the get_search_search_item_list() method, default values like moid, object_type are available, but Serial_number is not retrievable. 

As you can see that from the output we can get moid, object_type and class_id attributes, but as we try to extract 'Serial' from this data structure it fails. It appears that 'Serial' member is not implemented for retrieval.

As seen in following code and result:

>>> search_list = serach_instance.get_search_search_item_list(**kwargs)
>>>
>>>search_list
{'object_type': 'search.SearchItem.List',
 'results': [{'Model': 'UCSB-B200-M3',
              'Serial': 'FCH1716JA0X',
              'class_id': 'compute.Blade',
              'moid': '60df380f6176752d308e7294',
              'object_type': 'compute.Blade'},
             {'Model': 'UCSB-B200-M3',
              'Name': '[nyhmps3esx008.verizon.com](http://nyhmps3esx008.verizon.com/)',
              'Serial': 'FCH1716JA0X',
              'class_id': 'virtualization.VmwareHost',
              'moid': '6112fe46736c6f2d30e6ed70',
              'object_type': 'virtualization.VmwareHost'}]}
>>>
>>> search_list['results']
[{'Model': 'UCSB-B200-M3',
 'Serial': 'FCH1716JA0X',
 'class_id': 'compute.Blade',
 'moid': '60df380f6176752d308e7294',
 'object_type': 'compute.Blade'}, {'Model': 'UCSB-B200-M3',
 'Name': '[nyhmps3esx008.verizon.com](http://nyhmps3esx008.verizon.com/)',
 'Serial': 'FCH1716JA0X',
 'class_id': 'virtualization.VmwareHost',
 'moid': '6112fe46736c6f2d30e6ed70',
 'object_type': 'virtualization.VmwareHost'}]
>>>
>>>search_list['results'][0].moid
'60df380f6176752d308e7294'
>>>search_list['results'][0].object_type
'compute.Blade'
>>>search_list['results'][0].Serial
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\manahry\AppData\Roaming\Python\Python39\site-packages\intersight_openapi-1.0.9.3942-py3.9.egg\intersigh
t\model_utils.py", line 496, in __getitem__
  File "C:\Users\manahry\AppData\Roaming\Python\Python39\site-packages\intersight_openapi-1.0.9.3942-py3.9.egg\intersigh
t\model_utils.py", line 476, in get
  File "C:\Users\manahry\AppData\Roaming\Python\Python39\site-packages\intersight_openapi-1.0.9.3942-py3.9.egg\intersigh
t\model_utils.py", line 498, in __getitem__
intersight.exceptions.ApiAttributeError: SearchSearchItem has no attribute '0' at ['['received_data', 'results', 0]']**

**Comment by chaudharyrr** [comment]
Any updates on this ticket??

**Comment by the-akhil-nair** [comment]
Thank you for reaching out to us.

You can omit the client-side validation and then you can access the specific property.

```python
search_list = search_instance.get_search_search_item_list(_check_return_type=False,**kwargs)
print(search_list.results[0]["Serial"])
```

Please let us know if it fixes the problem.

**Comment by chaudharyrr** [comment]
This approach works fine to access that specific property.

thanks !!

**Comment by chaudharyrr** [comment]
Closing this ticket as workaround provided
