### ISSUE TITLE
Change the python SDK signing method to allow an alternative form of the Key to be referenced

### ISSUE THREAD

**Issue by dsoper2** [CiscoDevNet/intersight-python#35]
Enhancement request to update the signing.HttpSigningConfiguration method to allow an alternative form of the Key to be referenced (stringIO, etc) instead of having to store a local text/crt file and reference its path via the private_key_path parameter.

**Comment by vvb** [comment]
This is completed. Refer https://github.com/CiscoDevNet/intersight-python/blob/main/README.md#authentication
