### ISSUE TITLE
import intersight dont work

### ISSUE THREAD

**Issue by tjanitsc** [CiscoDevNet/intersight-python#41]
import intersight dont work

I installed Python and pip install git+https://github.com/CiscoUcs/intersight-python.git, also python setup.py install --user

when i start python and try to import intersight, i get the error:

TJANITSC-M-66SF:~ tjanitsc$ python3
Python 3.10.9 (v3.10.9:1dd9be6584, Dec  6 2022, 14:37:36) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import intersight
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'intersight'
>>>

**Comment by tjanitsc** [comment]
I've done this, but it dont work, get already the error with missing modules (intersight and intersight-api_client...

**Comment by the-akhil-nair** [comment]
Closing the issue as submitter is able to confirm that issue is fixed.
