### ISSUE TITLE
Include proxy in Authentication example

### ISSUE THREAD

**Issue by 3191110276** [CiscoDevNet/intersight-python#59]
The Authentication example does not include any proxy settings right now. It would be ideal if the function included the option for setting a proxy.

For example:
```
def get_api_client(api_key_id, api_secret_file = None, private_key_string=None, endpoint="https://intersight.com", proxy=""):
   ...
   if proxy != "":
      configuration.proxy = proxy

   return intersight.ApiClient(configuration)
```

**Comment by the-akhil-nair** [comment]
Following PR will allow end user to mention the proxy for their network configuration:
https://github.com/cisco-intersight/intersight_python_examples/pull/15

Closing the issue as the examples are now updated.
