### ISSUE TITLE
AttributeError: module 'intersight' has no attribute 'signing'

### ISSUE THREAD

**Issue by Raghulrp** [CiscoDevNet/intersight-python#61]
Hi, 

I am receiving this error "AttributeError: module 'intersight' has no attribute 'signing'". Can you please help on the same?

**Comment by mohamuni** [comment]
Hi @Raghulrp 

Can you please ellaborate on what operation you are trying to perform or share code snippet which is throwing error

**Comment by the-akhil-nair** [comment]
Thank you @Raghulrp  for reaching out to us.

Please let us know the following: 
1. The sample code used 
2. The intersight Python SDK version

Also, did you try using the latest version of the intersight Python SDK (v1.0.11.18012) ?
Please give a try and let us know if the problem persists.

**Comment by the-akhil-nair** [comment]
@Raghulrp Closing this issue for now as it is not reproducible.
If you think if it is still a bug please raise an issue with the sample code used.
